export const CREATE_BUDGET = 'CREATE_BUDGET'
export const ADD_BUDGET_ITEM = 'ADD_BUDGET_ITEM'
export const DELETE_BUDGET_ITEM = 'DELETE_BUDGET_ITEM'
export const UPDATE_BUDGET_ITEM = 'UPDATE_BUDGET_ITEM'
export const GET_BUDGET = 'GET_BUDGET'



export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'